apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: naglfar-imdb-importer-
spec:
  entrypoint: tipocket-imdb-importer
  arguments:
    parameters:
      - name: namespace # namespace
      - name: tag       # tag(different version uses different BRs), fill in: latest,tidb-4.0
      - name: test_cluster_name # cluster name import to
      - name: resource_request  # resource request name
      - name: workload_name     # workload node name
  templates:
    - name: tipocket-imdb-importer
      resource:
        action: create
        successCondition: status.state = finish
        manifest: |
          apiVersion: naglfar.pingcap.com/v1
          kind: TestWorkload
          metadata:
            name: imdb-importer
            namespace: {{workflow.parameters.namespace}}
          spec:
            clusterTopologies:
              - name: {{workflow.parameters.test_cluster_name}}
                aliasName: cluster
            workloads:
              - name: imdb-importer
                dockerContainer:
                  resourceRequest:
                    name: {{workflow.parameters.resource_request}}
                    node: {{workflow.parameters.workload_name}}
                  image: "hub.pingcap.net/mahjonp/bench-toolset:{{workflow.parameters.tag}}"
                  imagePullPolicy: Always
                  command:
                    - /bin/sh
                    - -c
                    - |
                      set -ex
                      export AWS_ACCESS_KEY_ID=minioadmin AWS_SECRET_ACCESS_KEY=minioadmin
                      tidb=`echo $cluster_tidb0 | awk -F ":" '{print $1}'`
                      path="s3://benchmark/imdb"
                      if [ "{{workflow.parameters.tag}}" = "tidb-4.0" ]; then
                        path="s3://benchmark/imdb-4.0"
                      fi
                      br restore db --db "imdb" --pd=$cluster_pd0 \
                              --storage=$path \
                              --s3.endpoint=http://172.16.5.109:9000 \
                              --send-credentials-to-tikv=true